name: .NET Tests PR Check

on:
  pull_request:
    branches:
      - main
      - master
      - '*'

jobs:
  unit-e2e-tests:
    runs-on: ubuntu-latest
    env:
      TEST_MODE: replay
      GOOGLE_API_KEY: test-key
      GOOGLE_CLOUD_PROJECT: test-project
      GOOGLE_CLOUD_LOCATION: us-central1

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          6.0.x
          8.0.x
    - name: List Recordings folder location
      run: |
        echo "Searching for Recordings folder..."
        find $GITHUB_WORKSPACE -type d -name 'Recordings'

    - name: Fake Google ADC
      run: |
        gcloud_config_path="${HOME}/.config/gcloud"
        mkdir -p "${gcloud_config_path}"
        cat > "${gcloud_config_path}/application_default_credentials.json" <<EOF
        { "client_id": "none", "client_secret": "none", "refresh_token": "none", "type": "authorized_user" }
        EOF

    - name: Show .NET version
      run: dotnet --list-sdks

    - name: Run Unit Tests
      run: dotnet test ./Google.GenAI.Tests
    
    - name: Run E2E Tests net6.0
      run: dotnet test ./Google.GenAI.E2E.Tests --framework net6.0

    - name: Run E2E Tests net8.0
      run: dotnet test ./Google.GenAI.E2E.Tests --framework net8.0
